apiVersion: v1
kind: Service
metadata:
  labels:
    app: otel-app
  name: otel-app
spec:
  type: ClusterIP
  ports:
  - port: 4000
    protocol: TCP
    targetPort: 3000
  selector:
    app: otel-app
